repos:
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/add-trailing-comma
    sha: v0.6.4
    hooks:
    -   id: add-trailing-comma
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.4
    hooks:
    -   id: no-commit-to-branch
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: double-quote-string-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: 'backend/(db_models/models.py|manage.py|backend/settings.py)'
    -   id: mixed-line-ending
        args: [--fix=lf]
